project_id = "azusa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[analytics]
enabled = false

# [functions.profiles]
# enabled = true
# verify_jwt = true
# import_map = "./functions/profiles/deno.json"
# # Uncomment to specify a custom file path to the entrypoint.
# # Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# entrypoint = "./functions/profiles/index.ts"
# # Specifies static files to be bundled with the function. Supports glob patterns.
# # For example, if you want to serve static HTML pages in your function:
# # static_files = [ "./functions/profiles/*.html" ]

# [functions.settings]
# enabled = true
# verify_jwt = true
# import_map = "./functions/settings/deno.json"
# # Uncomment to specify a custom file path to the entrypoint.
# # Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# entrypoint = "./functions/settings/index.ts"
# # Specifies static files to be bundled with the function. Supports glob patterns.
# # For example, if you want to serve static HTML pages in your function:
# # static_files = [ "./functions/settings/*.html" ]

# [functions.characters]
# enabled = true
# verify_jwt = true
# import_map = "./functions/characters/deno.json"
# # Uncomment to specify a custom file path to the entrypoint.
# # Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# entrypoint = "./functions/characters/index.ts"
# # Specifies static files to be bundled with the function. Supports glob patterns.
# # For example, if you want to serve static HTML pages in your function:
# # static_files = [ "./functions/characters/*.html" ]

# [functions.contacts]
# enabled = true
# verify_jwt = true
# import_map = "./functions/contacts/deno.json"
# # Uncomment to specify a custom file path to the entrypoint.
# # Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# entrypoint = "./functions/contacts/index.ts"
# # Specifies static files to be bundled with the function. Supports glob patterns.
# # For example, if you want to serve static HTML pages in your function:
# # static_files = [ "./functions/contacts/*.html" ]

# [functions.chats]
# enabled = true
# verify_jwt = true
# import_map = "./functions/chats/deno.json"
# # Uncomment to specify a custom file path to the entrypoint.
# # Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# entrypoint = "./functions/chats/index.ts"
# # Specifies static files to be bundled with the function. Supports glob patterns.
# # For example, if you want to serve static HTML pages in your function:
# # static_files = [ "./functions/chats/*.html" ]
